export const initialReportForm = {
  missionTitle: "",
  departureDate: "",
  returnDate: "",
  missionPlace: "",
  mission: "",
  name: "",
  phone: "",
  gender: "",
  role: "",
  vehicleBrand: "",
  vehiclePlate: "",
  vehicleCount: "",
  vehiclePlanCount: "",
  vehicleActualCount: "",
  equipmentType: "",
  equipmentCount: "",
  equipmentPlanCount: "",
  equipmentActualCount: "",
  departDate: "",
  arriveDate: "",
  routeDistance: "",
  travelDuration: "",
  planCount: "",
  actualCount: "",
  meetingParticipantsCount: "",
  meetingParticipantsFemale: "",
  meetingStartTime: "",
  meetingEndTime: "",
  lodgingPlace: "",
  lodgingCount: "",
  lodgingFemale: "",
  breakfastPlace: "",
  breakfastCount: "",
  breakfastFemale: "",
  breakfastPaymentUnit: "",
  breakfastSponsor: "",
  lunchPlace: "",
  lunchCount: "",
  lunchFemale: "",
  lunchPaymentUnit: "",
  lunchSponsor: "",
  dinnerPlace: "",
  dinnerCount: "",
  dinnerFemale: "",
  dinnerPaymentUnit: "",
  dinnerSponsor: "",
  implementationPlanTotal: "",
  implementationPlanFemale: "",
  implementationActualTotal: "",
  implementationActualFemale: "",
  implementationDurationCheck: "",
  implementationDurationManage: "",
  returnDepartTime: "",
  returnArriveTime: "",
  returnSafetyStatus: "",
  returnIssue: ""
};

export const reportNavItems = [
  { id: "request", label: "ស្នើសុំរថយន្ត" },
  { id: "policy", label: "គោលការណ៍" }
];

export const initialStatusText = "រួចរាល់សម្រាប់បង្កើតឯកសារ PDF";
